spring:
  datasource:
    url: jdbc:mysql://localhost:13306/sckorea
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
