name: ci-back

on:
  pull_request:
    branches:
      - dev
      - main
    paths: 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: repository checkout
        uses: actions/checkout@v3

      - name: install java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: assign grant gradlew
        run: chmod +x gradlew

      - name: test gradle
        run: ./gradlew --info test

      - name: Publish Test Results   
        uses: EnricoMi/publish-unit-test-result-action@v2     
        if: always()
        with:
          files: '**/build/test-results/test/TEST-*.xml'

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
